### ISSUE TITLE
Will you release the source code ?

### ISSUE THREAD

**Issue by mx8435** [swyoon/aaai2021-scene-graph-img-retr#2]

**Comment by williamwangus** [comment]
I emailed them when the paper was published since the github was empty. They told me they will first release the dataset and later the code... It has been 2 years and nothing else was released.

**Comment by swyoon** [comment]
@mx8435 @williamwangus 
I know this is a terribly late reply and sorry about leaving this repo empty.
The thing is the entire codebase was dependent on the company's codebase, and I left the company because the internship was finished.
I do have a zipped dump of my repository, so please check out. This will not be runnable because some important preprocessing steps are missing, but may help you figure out what was going on.
https://www.dropbox.com/s/wx6c9jw34r0p6l6/image-retrieval-coco_f30k.zip?dl=0

Thank you all for your attention on this work, and sorry for replying only now. Hope this helps.
