### ISSUE TITLE
Release of dataset

### ISSUE THREAD

**Issue by arnondagan** [swyoon/aaai2021-scene-graph-img-retr#3]
Will you also release the images ? and the different predictions from baselines and your models ?

**Comment by swyoon** [comment]
Dear @arnondagan ,

Since the images are derived from coco and visual genome, I am not able to upload the images directly. However, you can find the list of images in the following file. Hope this helps.

https://github.com/swyoon/image-retrieval/blob/coco_f30k/img_split.json

Unfortunately, I don't have the prediction files currently.
